name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        printf "%s\n" "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Build with Gradle
      run: ./gradlew clean build -x test

    - name: Copy jar to EC2
      run: |
        scp -i ~/.ssh/id_rsa build/libs/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USER }}/${{ secrets.JAR_NAME }}

    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
        pkill -f '${{ secrets.JAR_NAME }}' || true
        nohup java -jar -Dspring.profiles.active=${{ secrets.SPRING_PROFILE }} /home/${{ secrets.EC2_USER }}/${{ secrets.JAR_NAME }} > app.log 2>&1 &
        EOF
